services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data # Persistência de dados
volumes:
  redis-data: